version: '3'
services:

  mongo-server:
    container_name: mongodb
    image: mongo
    env_file:
      - docker.env
    ports:
      - 27017:27017
    volumes:
      - /Users/supertree/data/mongo:/data/db