version: '3'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - docker.env
    networks:
      - marketplace

networks:
  marketplace:
    driver: bridge