version: '3'

services:
    db:
        image: postgres
        container_name: db
        restart: always
        ports: 
            - '5432:5432'
        env_file:
            - docker.env
    test-db:
        image: postgres
        container_name: test-db
        restart: always
        ports:
            - '5433:5432'
        env_file:
            - docker.env
